### ISSUE TITLE
USB+HDMI only variant? Or PS2+VGA only?

### ISSUE THREAD

**Issue by lf94** [dhansel/VersaTerm#10]
It'd be amazing to have this shrunk down to just USB and HDMI - these technologies will most likely have many backward compatible devices created for them in the future, just as VGA and PS2 do.

On the other hand, PS2 and VGA are vastly simpler and will probably have the same types of devices for them forever too.

What do you think? I really like that this has a Pi Pico at its core. The other variants have PIC32s....

**Comment by dhansel** [comment]
It should actually be pretty easy to remove hardware features of VersaTerm. The [schematic ](https://github.com/dhansel/VersaTerm/blob/main/hardware/PCB/VersaTermSchematic.pdf)is fairly modular, you can just leave out (i.e. not solder onto the PCB) any of the following:
- PS/2 connector and all components connected to it in the schematic
- VGA connector and all resistors connected to it in the schematic
- USB keyboard connector
- HDMI connector and all resistors connected to it in the schematic
- RS232 connector and all components connected to it in the schematic
- TTL serial connector and all components connected to it in the schematic
- Buzzer and all components connected to it in the schematic

The firmware won't care that these are missing. That way you can save some money by not adding features you don't want.

I personally don't have a use for such a reduced version - my goal was to have something versatile that will work with whatever monitor/keyboard combination and serial port I am working with. So I don't think I will design and test build PCB layouts for different combinations of hardware features which I don't need. 

But the schematic and current layout (including an EasyEDA backup of the current schematics that can be imported and edited) is [available](https://github.com/dhansel/VersaTerm/tree/main/hardware/PCB) so maybe someone else (you?) wants to take a stab at this. It's a DIY project after all :)

**Comment by lf94** [comment]
Fair! I have zero experience with PCB design and just thought maybe it'd be an easy job :) I can take a shot for sure! I guess I will learn a lot.
