### ISSUE TITLE
Circuit schematic (pdf) doesn't render

### ISSUE THREAD

**Issue by n6502** [dhansel/VersaTerm#5]
Hi David
Trying to view the VersaTerm schematic (pdf) within github doesn't render. Downloading to my PC, trying to open, my pdf reader reports file as invalid.
Thanks
Nigel

**Comment by dhansel** [comment]
Hi Nigel,

I just tried this here and it renders just fine for me, in GitHub as well as after downloading:
https://github.com/dhansel/VersaTerm/blob/main/hardware/PCB/VersaTermSchematic.pdf

Can you try again - maybe it was a temporary glitch in GitHub?

David

**Comment by n6502** [comment]
Hi David

Many thanks for checking this out, and for your very prompt reply.
I've successfully viewed the embedded pdf in another (chrome) browser on a tablet, so the issue appears related to my PC (running Opera).
Weirdly, I can now download the pdf to my PC (using Opera) and open it in my pdf reader, but checking other projects with pdf files, it seems I can't view embed pdfs. Hey ho - technology...
This issue can be closed - apologies for taking your time.
Regards
Nigel

**Comment by dhansel** [comment]
No worries, glad you figured it out!
