### ISSUE TITLE
The requirements to build from source could use a couple more steps

### ISSUE THREAD

**Issue by un-clouded** [dhansel/VersaTerm#6]
When it said to me:

    arm-none-eabi-gcc: fatal error: cannot read spec file 'nosys.specs': No such file or directory

I replied:

    apt install libnewlib-arm-none-eabi

And when it said:

    fatal error: cassert: No such file or directory

I retorted:

    apt install libstdc++-arm-none-eabi-dev

And then it complained that:

    /usr/lib/gcc/arm-none-eabi/12.2.1/../../../arm-none-eabi/bin/ld: cannot find -lstdc++: No such file or directory

And I spake thusly:

    apt install libstdc++-arm-none-eabi-newlib

These are already in `lib/pico-sdk/README.md`, but it'd be super handy to have them at the top level too.  Thanks heaps!

**Comment by dhansel** [comment]
Thanks for the report! I've added your solutions to the Readme file!
